### ISSUE TITLE
Netcast '13 TV appears to have connected - even though it hasn't

### ISSUE THREAD

**Issue by snikk** [ConnectSDK/Connect-SDK-Android-API-Sampler#6] opened 2014-04-21 21:09 UTC
In sample app - connect to '13 TV, when pairing dialogue appears - press cancel. Note the pin code is still on tv. Press Connect and pick the '13 TV once again. Notice the app doesn't ask for pin code.

**Comment by khk624** [comment] 2015-02-10 05:39
I cannot reproduce this anymore. In the latest code, we already handled the pin code cancel case correctly. 
I'm going to close this.

**Closed by khk624** 2015-02-10 05:39 UTC
Labels: bug
